# Generated by Django 4.2.3 on 2023-07-18 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snacks', 'snacks')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Углеводы')),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Жиры')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Белки')),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Калории')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('category', models.ManyToManyField(to='calories_calc.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserFooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('fooditem', models.ManyToManyField(to='calories_calc.fooditem')),
            ],
        ),
    ]
