# Generated by Django 4.2.3 on 2023-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='customer',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Количество в граммах'),
        ),
    ]
