# Generated by Django 4.2.3 on 2023-07-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0003_userfooditem_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
