# Generated by Django 4.2.3 on 2023-07-20 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories_calc', '0004_alter_fooditem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfooditem',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserFoodItemAltern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooditem', models.ManyToManyField(to='calories_calc.fooditem')),
            ],
        ),
    ]
