# Generated by Django 4.2.3 on 2023-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0005_alter_userfooditem_customer_userfooditemaltern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.AddField(
            model_name='userfooditem',
            name='category',
            field=models.ManyToManyField(to='calories_calc.category'),
        ),
    ]
