# Generated by Django 4.2.3 on 2023-07-27 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories_calc', '0007_fooditem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFoodItem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories_calc.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories_calc.fooditem')),
            ],
        ),
    ]
