# Generated by Django 4.2.3 on 2023-07-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0008_userfooditem2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditemaltern',
            name='fooditem',
        ),
        migrations.DeleteModel(
            name='UserFoodItem2',
        ),
        migrations.DeleteModel(
            name='UserFoodItemAltern',
        ),
    ]
