# Generated by Django 4.2.3 on 2023-07-28 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0009_remove_userfooditemaltern_fooditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
