# Generated by Django 4.2.3 on 2023-07-28 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0010_fooditem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfooditem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ManyToManyField(blank=True, to='calories_calc.category'),
        ),
    ]
