# Generated by Django 4.2.3 on 2023-07-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0011_userfooditem_date_alter_fooditem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfooditem',
            old_name='date',
            new_name='add_date',
        ),
    ]
