# Generated by Django 4.2.3 on 2023-08-03 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0012_rename_date_userfooditem_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
