# Generated by Django 4.2.3 on 2023-08-03 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0013_alter_fooditem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
        ),
    ]
