# Generated by Django 4.2.3 on 2023-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0014_choosedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfooditem',
            name='quantity',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Количество в граммах'),
        ),
    ]
