# Generated by Django 4.2.3 on 2023-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0015_userfooditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество в граммах'),
        ),
    ]
