# Generated by Django 4.2.3 on 2023-08-23 12:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories_calc', '0017_alter_fooditem_calorie_alter_fooditem_carbohydrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass', models.IntegerField(blank=True, default=1, null=True, verbose_name='1 стакан = 250г воды')),
                ('drink_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('customer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
