# Generated by Django 4.2.3 on 2023-09-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0018_watertracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='date',
        ),
    ]
