# Generated by Django 4.2.3 on 2023-09-03 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0021_remove_fooditem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
