# Generated by Django 4.2.3 on 2023-09-04 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories_calc', '0023_remove_fooditem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosedate',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
