# Generated by Django 4.2.3 on 2023-10-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0024_choosedate_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
    ]
