# Generated by Django 4.2.3 on 2023-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_calc', '0026_alter_userfooditem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertracker',
            name='glass',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Стаканы, 1 стакан = 250г воды'),
        ),
    ]
