# Generated by Django 4.2.3 on 2023-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='media/avatars/', verbose_name='Аватар'),
        ),
    ]
