# Generated by Django 4.2.3 on 2023-07-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
