# Generated by Django 4.2.3 on 2023-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity',
            field=models.CharField(choices=[('Минимальный', 'Минимальный'), ('Слабый', 'Слабый'), ('Умеренный', 'Умеренный'), ('Тяжелый', 'Тяжелый'), ('Экстремальный', 'Экстремальный')], default='Минимальный', help_text='Выберите ваш уровень активности.', max_length=100, verbose_name='Уровень активности'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Введите в формате ДД.ММ.ГГГГ', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='growth',
            field=models.IntegerField(default=0, help_text='Введите в сантиметрах', verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(default=0, help_text='Введите в килограммах', verbose_name='Вес'),
        ),
    ]
