# Generated by Django 4.2.3 on 2023-08-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_calories_alter_customuser_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='calories',
            field=models.IntegerField(default=0, help_text='Введите 0 чтобы рассчитать автоматически', verbose_name='Количество калорий в день'),
        ),
    ]
