# Generated by Django 4.2.3 on 2023-08-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighing_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата взвешивания')),
                ('user_weight', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
