# Generated by Django 4.2.3 on 2023-08-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_weighing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weighing',
            old_name='user_weight',
            new_name='user',
        ),
    ]
