# Generated by Django 4.2.3 on 2023-08-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_user_weight_weighing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighing',
            name='weight_value',
            field=models.FloatField(default=0, help_text='Введите в килограммах', verbose_name='Вес'),
        ),
    ]
