# Generated by Django 4.2.3 on 2023-09-01 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное поле. Не более 150 символов. Только буквы, цифры и символ _', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', message='Псевдоним может состоять только из латинских символов, цифр и символа _')], verbose_name='Имя пользователя'),
        ),
    ]
