# Generated by Django 4.2.3 on 2023-09-03 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_avatar_alter_customuser_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Этот адрес электронной почты занят.'}, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты'),
        ),
    ]
